name: MLProject CI

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pandas numpy scikit-learn seaborn matplotlib
          pip install virtualenv
          pip install mlflow==2.19.0
          pip install -r MLProject/requirements.txt

      - name: Run MLflow Project
        run: |
          mlflow run ./MLProject --env-manager=virtualenv
